server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: oauth2-server
  profiles:
    include:
      - redis
      - mongo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  config:  ${spring.config.location:classpath:config}/logback.xml

